/*
 *****Just a fun Project. But Hardware designing was challenging for a newbie like me ;)
 *****FIle: LEdDisplay.ino
 *****Author: Abhishek Prasad @dEvCuLa
 *****Year: 2016
 */
 
#define leds 36
#include<string.h>
int led[leds];
int len,count=0;
String temp="TEST STRING";

void setup() {
  led[0]=0;
  led[1]=22,led[2]=23,led[3]=24,led[4]=25,led[5]=26;
  led[6]=27,led[7]=28,led[8]=29,led[9]=30,led[10]=31;
  led[11]=32,led[12]=33,led[13]=34,led[14]=35,led[15]=36;
  led[16]=37,led[17]=38,led[18]=39,led[19]=40,led[20]=41;
  led[21]=42,led[22]=43,led[23]=44,led[24]=45,led[25]=46;
  led[26]=47,led[27]=48,led[28]=49,led[29]=50,led[30]=51;
  led[31]=52,led[32]=53,led[33]=2,led[34]=3,led[35]=4;
  for(int i=1;i<leds;i++)
    {pinMode(led[i],OUTPUT);}
    len=temp.length();
}

void off()
{
  for(int i=1;i<leds;i++)
    digitalWrite(led[i],LOW);
}

void sadface()
{
  digitalWrite(led[27],HIGH);
  digitalWrite(led[31],HIGH);
  digitalWrite(led[35],HIGH);
  digitalWrite(led[28],HIGH);
  digitalWrite(led[29],HIGH);
  digitalWrite(led[6],HIGH);
  digitalWrite(led[7],HIGH);
  digitalWrite(led[11],HIGH);
  digitalWrite(led[12],HIGH);
  digitalWrite(led[9],HIGH);
  digitalWrite(led[10],HIGH);
  digitalWrite(led[14],HIGH);
  digitalWrite(led[15],HIGH);
}
void animation()
{
  //if(count==1)
  for(int i=0;i<4;i++){
  {
  digitalWrite(led[1],HIGH);
  digitalWrite(led[2],HIGH);
  digitalWrite(led[8],HIGH);
  digitalWrite(led[4],HIGH);
  digitalWrite(led[5],HIGH);
  digitalWrite(led[6],HIGH);
  digitalWrite(led[12],HIGH);
  digitalWrite(led[18],HIGH);
  digitalWrite(led[14],HIGH);
  digitalWrite(led[10],HIGH);
  }
  delay(300);
  off();
  {
  digitalWrite(led[6],HIGH);
  digitalWrite(led[7],HIGH);
  digitalWrite(led[13],HIGH);
  digitalWrite(led[9],HIGH);
  digitalWrite(led[10],HIGH);
  digitalWrite(led[11],HIGH);
  digitalWrite(led[17],HIGH);
  digitalWrite(led[23],HIGH);
  digitalWrite(led[19],HIGH);
  digitalWrite(led[15],HIGH);
  }
  delay(300);
  off();
  {
  digitalWrite(led[12],HIGH);
  digitalWrite(led[18],HIGH);
  digitalWrite(led[14],HIGH);
  digitalWrite(led[16],HIGH);
  digitalWrite(led[20],HIGH);
  digitalWrite(led[22],HIGH);
  digitalWrite(led[28],HIGH);
  digitalWrite(led[24],HIGH);
  digitalWrite(led[11],HIGH);
  digitalWrite(led[15],HIGH);
  }
  delay(300);
  off();
  {
  digitalWrite(led[16],HIGH);
  digitalWrite(led[17],HIGH);
  digitalWrite(led[23],HIGH);
  digitalWrite(led[19],HIGH);
  digitalWrite(led[20],HIGH);
  digitalWrite(led[21],HIGH);
  digitalWrite(led[27],HIGH);
  digitalWrite(led[33],HIGH);
  digitalWrite(led[29],HIGH);
  digitalWrite(led[25],HIGH);
  }
  delay(300);
  off(); 
  }
}
void display(char arg)
{
  off();
  switch(arg)
  {
    case 'A':{
      digitalWrite(led[31],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[7],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[9],HIGH);
      digitalWrite(led[15],HIGH);
      digitalWrite(led[17],HIGH);
      digitalWrite(led[18],HIGH);
      digitalWrite(led[19],HIGH);
      digitalWrite(led[20],HIGH);
      digitalWrite(led[25],HIGH);
      digitalWrite(led[30],HIGH);
      digitalWrite(led[35],HIGH);
      break;
    }
    case 'B':{
      digitalWrite(led[1],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[35],HIGH);
      digitalWrite(led[2],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[10],HIGH);
      digitalWrite(led[15],HIGH);
      digitalWrite(led[19],HIGH);
      digitalWrite(led[18],HIGH);
      digitalWrite(led[17],HIGH);
      digitalWrite(led[25],HIGH);
      digitalWrite(led[30],HIGH);
      digitalWrite(led[34],HIGH);
      digitalWrite(led[33],HIGH);
      digitalWrite(led[32],HIGH);
      break;
    }
    case 'C':{
      digitalWrite(led[5],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[2],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[32],HIGH);
      digitalWrite(led[33],HIGH);
      digitalWrite(led[34],HIGH);
      digitalWrite(led[31],HIGH);
      break;
    }
    case 'D':{
      digitalWrite(led[35],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[1],HIGH);
      digitalWrite(led[2],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[9],HIGH);
      digitalWrite(led[15],HIGH);
      digitalWrite(led[20],HIGH);
      digitalWrite(led[25],HIGH);
      digitalWrite(led[29],HIGH);
      digitalWrite(led[33],HIGH);
      digitalWrite(led[34],HIGH);
      break;
    }
    case 'E':{
      digitalWrite(led[5],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[2],HIGH);
      digitalWrite(led[1],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[31],HIGH);
      digitalWrite(led[32],HIGH);
      digitalWrite(led[33],HIGH);
      digitalWrite(led[34],HIGH);
      digitalWrite(led[35],HIGH);
      digitalWrite(led[17],HIGH);
      digitalWrite(led[18],HIGH);
      digitalWrite(led[19],HIGH);
      digitalWrite(led[20],HIGH);
      break;
    }
    case 'F':{
      digitalWrite(led[5],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[2],HIGH);
      digitalWrite(led[1],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[35],HIGH);
      digitalWrite(led[17],HIGH);
      digitalWrite(led[18],HIGH);
      digitalWrite(led[19],HIGH);
      digitalWrite(led[20],HIGH);
      break;
    }
    case 'G':{
      digitalWrite(led[5],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[2],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[32],HIGH);
      digitalWrite(led[33],HIGH);
      digitalWrite(led[34],HIGH);
      digitalWrite(led[35],HIGH);
      digitalWrite(led[30],HIGH);
      digitalWrite(led[25],HIGH);
      digitalWrite(led[20],HIGH);
      digitalWrite(led[19],HIGH);
      digitalWrite(led[18],HIGH);
      break;
    }
    case 'H':{
      digitalWrite(led[1],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[31],HIGH);
      digitalWrite(led[17],HIGH);
      digitalWrite(led[18],HIGH);
      digitalWrite(led[19],HIGH);
      digitalWrite(led[10],HIGH);
      digitalWrite(led[15],HIGH);
      digitalWrite(led[20],HIGH);
      digitalWrite(led[25],HIGH);
      digitalWrite(led[30],HIGH);
      digitalWrite(led[35],HIGH);
      digitalWrite(led[5],HIGH);
      break;
    }
    case 'I':{
      digitalWrite(led[5],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[2],HIGH);
      digitalWrite(led[1],HIGH);
      digitalWrite(led[31],HIGH);
      digitalWrite(led[32],HIGH);
      digitalWrite(led[33],HIGH);
      digitalWrite(led[34],HIGH);
      digitalWrite(led[35],HIGH);
      digitalWrite(led[8],HIGH);
      digitalWrite(led[13],HIGH);
      digitalWrite(led[18],HIGH);
      digitalWrite(led[23],HIGH);
      digitalWrite(led[28],HIGH);
      break;
    }
    case 'L':{
      digitalWrite(led[1],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[31],HIGH);
      digitalWrite(led[32],HIGH);
      digitalWrite(led[33],HIGH);
      digitalWrite(led[34],HIGH);
      digitalWrite(led[35],HIGH);
      break;
    }
    case 'K':{
      digitalWrite(led[1],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[35],HIGH);
      digitalWrite(led[12],HIGH);
      digitalWrite(led[8],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[22],HIGH);
      digitalWrite(led[28],HIGH);
      digitalWrite(led[32],HIGH);
      break;
    }
    case 'N':{
      digitalWrite(led[1],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[31],HIGH);
      digitalWrite(led[7],HIGH);
      digitalWrite(led[18],HIGH);
      digitalWrite(led[29],HIGH);
      digitalWrite(led[10],HIGH);
      digitalWrite(led[15],HIGH);
      digitalWrite(led[20],HIGH);
      digitalWrite(led[25],HIGH);
      digitalWrite(led[30],HIGH);
      digitalWrite(led[35],HIGH);
      digitalWrite(led[5],HIGH);
      break;
    }
    case 'S':{
      digitalWrite(led[5],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[2],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[17],HIGH);
      digitalWrite(led[18],HIGH);
      digitalWrite(led[19],HIGH);
      digitalWrite(led[25],HIGH);
      digitalWrite(led[30],HIGH);
      digitalWrite(led[35],HIGH);
      digitalWrite(led[32],HIGH);
      digitalWrite(led[33],HIGH);
      digitalWrite(led[34],HIGH);
      break;
    }
    case 'P':{
      digitalWrite(led[1],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[35],HIGH);
      digitalWrite(led[2],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[10],HIGH);
      digitalWrite(led[15],HIGH);
      digitalWrite(led[19],HIGH);
      digitalWrite(led[18],HIGH);
      digitalWrite(led[17],HIGH);
      break;
    }
    case 'J':{
      digitalWrite(led[5],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[2],HIGH);
      digitalWrite(led[1],HIGH);
      digitalWrite(led[9],HIGH);
      digitalWrite(led[14],HIGH);
      digitalWrite(led[19],HIGH);
      digitalWrite(led[24],HIGH);
      digitalWrite(led[29],HIGH);
      digitalWrite(led[33],HIGH);
      digitalWrite(led[34],HIGH);
      digitalWrite(led[26],HIGH);
      break;
    }
    case 'M':{
      digitalWrite(led[1],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[31],HIGH);
      digitalWrite(led[7],HIGH);
      digitalWrite(led[13],HIGH);
      digitalWrite(led[9],HIGH);
      digitalWrite(led[5],HIGH);
      digitalWrite(led[10],HIGH);
      digitalWrite(led[15],HIGH);
      digitalWrite(led[20],HIGH);
      digitalWrite(led[25],HIGH);
      digitalWrite(led[30],HIGH);
      digitalWrite(led[35],HIGH);
      break;
    }
    case 'O':{
      digitalWrite(led[2],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[10],HIGH);
      digitalWrite(led[15],HIGH);
      digitalWrite(led[20],HIGH);
      digitalWrite(led[25],HIGH);
      digitalWrite(led[30],HIGH);
      digitalWrite(led[32],HIGH);
      digitalWrite(led[33],HIGH);
      digitalWrite(led[34],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[26],HIGH);
      break;
    }
    case 'U':{
      digitalWrite(led[1],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[32],HIGH);
      digitalWrite(led[33],HIGH);
      digitalWrite(led[34],HIGH);
      digitalWrite(led[5],HIGH);
      digitalWrite(led[10],HIGH);
      digitalWrite(led[15],HIGH);
      digitalWrite(led[20],HIGH);
      digitalWrite(led[25],HIGH);
      digitalWrite(led[30],HIGH);
      break;
    }
    case 'R':{
      digitalWrite(led[1],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[31],HIGH);
      digitalWrite(led[2],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[10],HIGH);
      digitalWrite(led[15],HIGH);
      digitalWrite(led[19],HIGH);
      digitalWrite(led[18],HIGH);
      digitalWrite(led[17],HIGH);
      digitalWrite(led[23],HIGH);
      digitalWrite(led[29],HIGH);
      digitalWrite(led[35],HIGH);
      break;
    }
    case 'T':{
      digitalWrite(led[5],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[2],HIGH);
      digitalWrite(led[1],HIGH);
      digitalWrite(led[8],HIGH);
      digitalWrite(led[13],HIGH);
      digitalWrite(led[18],HIGH);
      digitalWrite(led[23],HIGH);
      digitalWrite(led[28],HIGH);
      digitalWrite(led[33],HIGH);
      break;
    }
    case 'V':{
      digitalWrite(led[1],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[27],HIGH);
      digitalWrite(led[33],HIGH);
      digitalWrite(led[29],HIGH);
      digitalWrite(led[25],HIGH);
      digitalWrite(led[5],HIGH);
      digitalWrite(led[10],HIGH);
      digitalWrite(led[15],HIGH);
      digitalWrite(led[20],HIGH);
      break;
     }
     case 'W':{
      digitalWrite(led[1],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[31],HIGH);
      digitalWrite(led[10],HIGH);
      digitalWrite(led[15],HIGH);
      digitalWrite(led[20],HIGH);
      digitalWrite(led[25],HIGH);
      digitalWrite(led[30],HIGH);
      digitalWrite(led[35],HIGH);
      digitalWrite(led[5],HIGH);
      digitalWrite(led[27],HIGH);
      digitalWrite(led[23],HIGH);
      digitalWrite(led[29],HIGH);
      break;
     }
     case 'X':{
      digitalWrite(led[1],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[12],HIGH);
      digitalWrite(led[18],HIGH);
      digitalWrite(led[24],HIGH);
      digitalWrite(led[30],HIGH);
      digitalWrite(led[35],HIGH);
      digitalWrite(led[5],HIGH);
      digitalWrite(led[10],HIGH);
      digitalWrite(led[14],HIGH);
      digitalWrite(led[22],HIGH);
      digitalWrite(led[26],HIGH);
      digitalWrite(led[31],HIGH);
      break;
     }
     case 'Y':{
      digitalWrite(led[1],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[12],HIGH);
      digitalWrite(led[18],HIGH);
      digitalWrite(led[5],HIGH);
      digitalWrite(led[10],HIGH);
      digitalWrite(led[14],HIGH);
      digitalWrite(led[23],HIGH);
      digitalWrite(led[28],HIGH);
      digitalWrite(led[33],HIGH);
      break;
     }
     case 'Z':{
      digitalWrite(led[5],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[2],HIGH);
      digitalWrite(led[1],HIGH);
      digitalWrite(led[31],HIGH);
      digitalWrite(led[32],HIGH);
      digitalWrite(led[33],HIGH);
      digitalWrite(led[34],HIGH);
      digitalWrite(led[35],HIGH);
      digitalWrite(led[9],HIGH);
      digitalWrite(led[18],HIGH);
      digitalWrite(led[27],HIGH);
      break;
     }
     case 'Q':{
      digitalWrite(led[2],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[10],HIGH);
      digitalWrite(led[15],HIGH);
      digitalWrite(led[20],HIGH);
      digitalWrite(led[25],HIGH);
      digitalWrite(led[29],HIGH);
      digitalWrite(led[28],HIGH);
      digitalWrite(led[27],HIGH);
      digitalWrite(led[21],HIGH);
      digitalWrite(led[16],HIGH);
      digitalWrite(led[11],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[23],HIGH);
      digitalWrite(led[31],HIGH);
      break;
     }
     case ' ':{
      digitalWrite(led[18],HIGH);
      break;
     }
     case '.':{
      digitalWrite(led[33],HIGH);
      break;
     }
     case ',':{
      digitalWrite(led[23],HIGH);
      digitalWrite(led[28],HIGH);
      digitalWrite(led[34],HIGH);
      break;
     }
     case '?':{
      digitalWrite(led[11],HIGH);
      digitalWrite(led[6],HIGH);
      digitalWrite(led[2],HIGH);
      digitalWrite(led[3],HIGH);
      digitalWrite(led[4],HIGH);
      digitalWrite(led[10],HIGH);
      digitalWrite(led[15],HIGH);
      digitalWrite(led[19],HIGH);
      digitalWrite(led[23],HIGH);
      digitalWrite(led[28],HIGH);
      digitalWrite(led[33],HIGH);
      break;
     }
     default:{
      for(int i=0;i<leds;i++)
      digitalWrite(led[i],HIGH);
     }
  }
}
void loop() {
  animation();
  //count++;
  for(int i=0;i<len;i++)
  {
    display(temp[i]);
    delay(1000);
    off();
    delay(100);
  }
  delay(1500);
  off();
  //count--;
  //animation();
  //count++;
}
